# Generated by Django 4.0.4 on 2024-06-03 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('is_credit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('semester', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ПР', 'Программная инженерия'), ('ПИ', 'Прикладная информатика'), ('ИВ', 'Информатика и вычислительная техника'), ('ИБ', 'Информационная безопасность'), ('УС', 'Управление в технических системах'), ('КБ', 'Компьютерная безопасность'), ('АС', 'Безопасность автоматизированных систем')], max_length=2)),
                ('code', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'speciality',
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Speciality_Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.discipline')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.speciality')),
            ],
            options={
                'db_table': 'speciality_discipline',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.speciality_discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.teacher')),
            ],
            options={
                'db_table': 'teacher_discipline',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.group')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.speciality'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.student')),
                ('teacher_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.teacher_discipline')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
