# Generated by Django 4.0.4 on 2024-06-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholarship_coefficient',
            field=models.FloatField(default=1.0),
        ),
    ]
